#!/usr/bin/env bash
#a script that stops the previous process

# Get the PID of the porgram
id=$(pgrep "bash ./4-to_infinity_and_beyond" -f)

# terminate the infinit process
if [ -n "$id" ]
then
	kill -15 "$id"
fi
