#!/usr/bin/env bash

# Update package list and install UFW
sudo apt update
sudo apt install ufw -y

# Allow incoming traffic on ports 22, 80, and 443
sudo ufw allow 22/tcp
sudo ufw allow 80/tcp
sudo ufw allow 443/tcp

# Enable UFW
sudo ufw enable

# Verify UFW status
sudo ufw status
